version: "3"

services:

  app:
    build: "."
    restart: "always"
    ports:
    - ${APP_PORT:-3000}:3000
    env_file:
    - ".env"
    volumes:
    - ".:/go/src/github.com/oysterprotocol/brokernode"
    working_dir: "/go/src/github.com/oysterprotocol/brokernode"
    command: >
      bash -c "
        echo ${DEBUG}
        if [ -z ${DEBUG} ]; then
          echo \"Starting Buffalo PROD mode\";
          # buffalo db migrate;
          buffalo build -o ./bin/brokernode && chmod +x ./bin/brokernode;
          ./bin/brokernode;

        else
          echo \"Starting Buffalo DEV mode\";
          # buffalo db migrate;
          buffalo dev;
        fi
      "
