[prune]
  go-tests = true
  non-go = true
  unused-packages = true

  [[prune.project]]
      name = "github.com/ethereum/go-ethereum"
      non-go = false
      unused-packages = false

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.43"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  # version = "1.5.4" TODO: Lock this on the next release.
  branch = "master"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.16"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.12.6"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.6.4"

[[constraint]]
  name = "github.com/gobuffalo/pop"
  version = "4.7.3"

[[constraint]]
  name = "github.com/gobuffalo/suite"
  version = "2.1.6"

[[constraint]]
  name = "github.com/gobuffalo/uuid"
  version = "2.0.3"

[[constraint]]
  name = "github.com/gobuffalo/validate"
  version = "2.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/gobuffalo/x"

[[constraint]]
  branch = "master"
  name = "github.com/iotaledger/giota"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/markbates/grift"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.5.0"

[[constraint]]
  name = "github.com/shopspring/decimal"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stackimpact/stackimpact-go"
  version = "2.3.10"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/secure"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/segmentio/analytics-go.v3"
  version = "3.0.0"
